/* Commands - Database */

CREATE DATABASE QUIOSQUE1;

USE QUIOSQUE1;

CREATE TABLE COLABORADOR(
	IDCOLABORADOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(200) NOT NULL,
	NASCIMENTO DATE NOT NULL, 
	EMAIL VARCHAR(200) UNIQUE NOT NULL,
	TELEFONE INT NOT NULL
);


CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	CEP INT NOT NULL,
	RUA VARCHAR(200) NOT NULL,
	BAIRRO VARCHAR(200) NOT NULL,
	NUMERO INT NOT NULL,
	CIDADE VARCHAR(200) NOT NULL,
	COMPLEMENTO VARCHAR(200),
	ID_COLABORADOR INT UNIQUE,
	FOREIGN KEY(ID_COLABORADOR)
	REFERENCES COLABORADOR(IDCOLABORADOR)
);


CREATE TABLE CATEGORIA(
	IDCATEGORIA INT PRIMARY KEY AUTO_INCREMENT,
	CATEGORIA VARCHAR(100) NOT NULL,
	CPF INT NOT NULL,
	RGCPF VARCHAR(1000) NOT NULL,
	OUTROS_ARQUIVOS VARCHAR(1000) NOT NULL,
	ID_COLABORADOR INT UNIQUE,
	FOREIGN KEY(ID_COLABORADOR)
	REFERENCES COLABORADOR(IDCOLABORADOR)
);


CREATE TABLE SETOR(
	IDSETOR INT PRIMARY KEY AUTO_INCREMENT,
	SETOR_ATUAR VARCHAR(100) NOT NULL,
	SETOR_ANTERIOR VARCHAR(100) NOT NULL,
	SEGUNDA_OPCAO VARCHAR(100) NOT NULL,
	ID_COLABORADOR INT UNIQUE,
	FOREIGN KEY(ID_COLABORADOR)
	REFERENCES COLABORADOR(IDCOLABORADOR)	
);


CREATE TABLE PRACA(
	IDPRACA INT PRIMARY KEY AUTO_INCREMENT,
	PRACA VARCHAR(100) NOT NULL,
	OUTRA_PRACA VARCHAR(100) NOT NULL,
	OPNIAO TEXT, 
	ID_COLABORADOR INT UNIQUE,
	FOREIGN KEY(ID_COLABORADOR)
	REFERENCES COLABORADOR(IDCOLABORADOR)
);



